spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/cure-connect-web1
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com
  application:
    name: cure-connect
    data:
      mongodb:
        uri: 
  server:
    port: '8080'